export enum EnumSelectors {
  BODY = 'body',

  HEADER_SEARCH_INPUT = '.gb_re',
  HEADER_ACTIVE_BUTTON = `header div[role="button"][jsaction]`,
  SIDEBAR = '.at9',
  EMAIL_LIST = '.nH.bkK',

  SETTINGS_BUTTON = '[aria-label="Settings"]',
  SETTINGS_BUTTON_ACTIVE = '[aria-label="Settings"][aria-expanded="true"]',
  SETTINGS_BUTTON_NOT_ACTIVE = '[aria-label="Settings"][aria-expanded="false"]',
  SETTINGS_BUTTON_CLOSE = '[aria-label="Quick settings"] [aria-label="Close"]',
  SETTINGS_SIDE_PANEL = '[aria-label="Quick settings"]',
  SETTINGS_SIDE_PANEL_PARENT = '.nH.bkK ~ .nH > div',
  SETTINGS_SIDE_PANEL_PREVENT_ELEMENTS = '[aria-label="Quick settings"] fieldset button:not([aria-label="Close"]), [aria-label="Quick settings"] fieldset label, [aria-label="Quick settings"] fieldset img[jsaction], [aria-label="Quick settings"] fieldset input',

  DENSITY_TITLE = '[aria-label="Display density"]',
  DENSITY_LABEL = '[aria-label="Display density"] ~ * label, [aria-label="Display density"] ~ label',
  DENSITY_ACTIVE = '[aria-label="Display density"] ~ * input:checked',
  DENSITY_DEFAULT = '[aria-label="Display density"] ~ * input[aria-label="Default"]',
  DENSITY_NOT_DEFAULT = '[aria-label="Display density"] ~ * input:not([aria-label="Default"])',
  DENSITY_DEFAULT_ACTIVE = '[aria-label="Display density"] ~ * input[aria-label="Default"]:checked',
  DENSITY_DEFAULT_NOT_ACTIVE = '[aria-label="Display density"] ~ * input[aria-label="Default"]:not(:checked)',
  DENSITY_COMFORTABLE = '[aria-label="Display density"] ~ * input[aria-label="Comfortable"]',
  DENSITY_COMPACT = '[aria-label="Display density"] ~ * input[aria-label="Compact"]',

  THEME_BACKGROUNDS_TITLE = '[aria-label="Theme"]',
  THEME_BACKGROUNDS_VIEW_ALL = '[aria-label="Theme"] + [aria-label="View all"]',
  THEME_BACKGROUNDS = 'div:has([aria-label="Theme"]) ~ * img',
  THEME_BACKGROUNDS_ACTIVE = 'div:has([aria-label="Theme"]) ~ * img.WU',
  THEME_BACKGROUNDS_DEFAULT = 'div:has([aria-label="Theme"]) ~ * img[aria-label="Default theme"]',
  THEME_BACKGROUNDS_NOT_DEFAULT = 'div:has([aria-label="Theme"]) ~ * img:not([aria-label="Default theme"])',
  THEME_BACKGROUNDS_DEFAULT_ACTIVE = 'div:has([aria-label="Theme"]) ~ * img[aria-label="Default theme"].WU',
  THEME_BACKGROUNDS_DEFAULT_NOT_ACTIVE = 'div:has([aria-label="Theme"]) ~ * img[aria-label="Default theme"]:not(.WU)',

  INBOX_TYPE_TITLE = '[aria-label="Inbox type"]',
  INBOX_TYPE_LABEL = '[aria-label="Inbox type"] ~ * label, [aria-label="Inbox type"] ~ label',
  INBOX_TYPE_DEFAULT_ACTIVE = '[aria-label="Inbox type"] ~ * input[aria-label="Default"]:checked',
  INBOX_TYPE_DEFAULT_NOT_ACTIVE = '[aria-label="Inbox type"] ~ * input[aria-label="Default"]:not(:checked)',

  READING_PANE_TITLE = '[aria-label="Reading pane"]',
  READING_PANE_LABEL = '[aria-label="Reading pane"] ~ * label, [aria-label="Reading pane"] ~ label',
  READING_PANE_DEFAULT_ACTIVE = '[aria-label="Reading pane"] ~ * input[aria-label="No split"]:checked',
  READING_PANE_DEFAULT_NOT_ACTIVE = '[aria-label="Reading pane"] ~ * input[aria-label="No split"]:not(:checked)',

  EMAIL_THREADING_TITLE = '[aria-label="Email threading"]',
  EMAIL_THREADING_LABEL = '[aria-label="Email threading"] ~ * label, [aria-label="Email threading"] ~ label',

  msg_items = "tr[jscontroller][aria-labelledby][role= 'row']",
  sender_cell = '.yX.xY',
  msg_cell = '.xY.a4W',
  reply_forward_btn = 'span[role="link"][jslog]',
  text_box = '.LW-avf',
  msg_container_wrap = '[data-message-id]',
  send_btn = `.gU .L3.aoO[role = 'button'][jslog]`,
  reply_buttons = 'tr.btC',
  profile_name_element = '.gb_wb',
  profile_image = '.gb_Ia, .gb_g',
  compose_window_floating = '.aaZ',
  COMPOSE_WINDOW = '.aoI',
  expand_waterfall_button = 'div.ajR',
  contenteditable_original = 'div[gmail_original]',
  contenteditable_quote = 'div[contenteditable]>div.gmail_quote',
  contenteditable = 'div[contenteditable]',
  visible_menu_items = `[role="menu"][aria-haspopup='true'][style*='visible'][tabindex='0'] [role="menuitem"]`,
  ctx_clickable = `[role="menuitem"]`,
  ctx_reply_icon = '.J-N-JX.aDE.BS',
  ctx_reply_all_icon = '.J-N-JX.aDE.BR',
  super_reply_button = '.super-reply-button',
  thread_page_reply_buttons = '.amn',

  gmail_google_account_full_name = '.gb_vb,.gb_Hb',
  gmail_contenteditable_original = 'div[gmail_original]',
  gmail_contenteditable_quote = 'div[contenteditable]>div.gmail_quote',
  gmail_contenteditable = 'div[contenteditable]',

  super_reply_btn = 'super-reply-btn',
  super_reply_btn_wrap = 'super-reply-btn-wrap',

  mock_mail_compose_window = '.mock-mail-thread',
  mock_mail_compose_send_button = '.mock-mail-reply-area-buttons button',
  mock_mail_thread_container = '.mock-mail-thread',
  mock_mail_thread_message = '.mock-mail-message',
  mock_mail_thread_message_text = '.mock-mail-message-text',
  mock_mail_thread_message_author = '.mock-mail-author',
  mock_mail_sender = '.mock-mail-profile-name',
}
